#!/usr/bin/env python3
"""
Multi-Agent Debate Orchestrator
Spawns sub-agents with different personas to debate a topic.
"""

import argparse
import json
import sys
import subprocess
import os
from pathlib import Path
from datetime import datetime

WORKSPACE = Path(os.environ.get("OPENCLAW_WORKSPACE", "/config/.openclaw/workspace"))

PERSONAS = {
    "researcher": {
        "emoji": "🔬",
        "name": "研究者",
        "prompt": "あなたは「研究者」ペルソナです。事実、証拠、データに基づいた分析を行ってください。学術的な厳密さを保ち、関連する研究や事例を引用してください。日本語で回答してください。"
    },
    "critic": {
        "emoji": "🔍",
        "name": "批評家",
        "prompt": "あなたは「批評家」ペルソナです。論理的な誤りや弱い議論を指摘し、反論や代替解釈を提示してください。建設的に前提に挑戦してください。日本語で回答してください。"
    },
    "practitioner": {
        "emoji": "🔧",
        "name": "実践者",
        "prompt": "あなたは「実践者」ペルソナです。実用的な適用可能性を評価し、実装上の課題を特定し、具体的なユースケースを提案してください。コスト/ベネフィットのトレードオフを考慮してください。日本語で回答してください。"
    },
    "visionary": {
        "emoji": "🎨",
        "name": "先見者",
        "prompt": "あなたは「先見者」ペルソナです。未来の可能性を想像し、分野を超えたアイデアの結びつけを行い、創造的な解決策を提案してください。現在の制限にとらわれず長期的な影響を考えてください。日本語で回答してください。"
    },
    "educator": {
        "emoji": "📚",
        "name": "教育者",
        "prompt": "あなたは「教育者」ペルソナです。複雑な概念を分かりやすく説明し、学習パスを提案し、例えや例を使って知識を構造化してください。日本語で回答してください。"
    },
}

DEFAULT_PERSONAS = ["researcher", "critic", "practitioner"]


def build_agent_task(persona_key: str, topic: str, context: str = "", round_num: int = 1) -> str:
    """Build the task prompt for a sub-agent."""
    persona = PERSONAS[persona_key]
    task = f"""{persona['prompt']}

## 議論トピック
{topic}

"""
    if context:
        task += f"""## 他のエージェントの意見（ラウンド{round_num}への参照）
{context}

これらの意見を踏まえて、あなたの視点から{300 + round_num * 100}字以内で議論に参加してください。
"""
    else:
        task += f"""
ラウンド{round_num}: あなたの視点から{300 + round_num * 100}字以内で分析してください。
"""
    
    task += """
## 出力形式
- 3〜5個の要点でまとめる
- 最後に一言で結論を述べる
"""
    return task


def save_debate(topic: str, results: list, output_dir: Path = None):
    """Save debate results to markdown."""
    now = datetime.now()
    if output_dir is None:
        output_dir = WORKSPACE / "memory" / "docs" / f"{now.year:04d}" / f"{now.month:02d}" / f"{now.day:02d}"
    output_dir.mkdir(parents=True, exist_ok=True)
    
    slug = topic[:30].replace(" ", "-").replace("/", "-")
    filepath = output_dir / f"debate-{slug}.md"
    
    content = f"""---
title: 🗣️ マルチエージェント議論 - {topic}
date: {now.strftime("%Y-%m-%d %H:%M")}
---

# 🗣️ マルチエージェント議論

## トピック
{topic}

## 参加ペルソナ
{chr(10).join(f"- {PERSONAS[r['persona']]['emoji']} {PERSONAS[r['persona']]['name']}" for r in results)}

---

"""
    for i, result in enumerate(results):
        p = PERSONAS[result["persona"]]
        content += f"## {p['emoji']} {p['name']} (ラウンド {result['round']})\n\n"
        content += f"{result['response']}\n\n---\n\n"
    
    content += f"\n---\n_Generated by multi-agent-debate skill_\n"
    
    filepath.write_text(content, encoding="utf-8")
    return filepath


def main():
    parser = argparse.ArgumentParser(description="Multi-Agent Debate Orchestrator")
    parser.add_argument("--topic", required=True, help="Debate topic")
    parser.add_argument("--personas", default=",".join(DEFAULT_PERSONAS), help="Comma-separated persona keys")
    parser.add_argument("--rounds", type=int, default=2, help="Number of debate rounds")
    parser.add_argument("--mode", choices=["paper", "idea", "decision"], default="idea", help="Debate mode")
    parser.add_argument("--topic-url", help="URL for paper/content to debate")
    parser.add_argument("--save", action="store_true", default=True, help="Save results to file")
    parser.add_argument("--json", action="store_true", help="Output as JSON")
    args = parser.parse_args()
    
    persona_keys = args.personas.split(",")
    for pk in persona_keys:
        if pk not in PERSONAS:
            print(f"Error: Unknown persona '{pk}'. Available: {', '.join(PERSONAS.keys())}", file=sys.stderr)
            sys.exit(1)
    
    topic = args.topic
    if args.topic_url:
        topic += f"\n\n参考資料: {args.topic_url}"
    
    results = []
    
    print(f"🎭 Starting debate: {args.topic}")
    print(f"📋 Personas: {', '.join(PERSONAS[pk]['emoji'] + ' ' + PERSONAS[pk]['name'] for pk in persona_keys)}")
    print(f"🔄 Rounds: {args.rounds}")
    print()
    
    for round_num in range(1, args.rounds + 1):
        print(f"--- Round {round_num} ---")
        
        for pk in persona_keys:
            # Build context from previous responses
            context_parts = []
            for r in results:
                p = PERSONAS[r["persona"]]
                context_parts.append(f"{p['emoji']} {p['name']}: {r['response'][:200]}...")
            context = "\n\n".join(context_parts) if context_parts else ""
            
            task = build_agent_task(pk, topic, context, round_num)
            
            print(f"  {PERSONAS[pk]['emoji']} Spawning {PERSONAS[pk]['name']}...", end=" ", flush=True)
            
            # For now, use a simple subprocess approach
            # In production, this would use sessions_spawn via OpenClaw
            result = {
                "persona": pk,
                "round": round_num,
                "response": task,  # Placeholder - actual execution happens via OpenClaw
            }
            results.append(result)
            print("done")
    
    # Save results
    if args.save:
        filepath = save_debate(args.topic, results)
        print(f"\n📁 Saved to: {filepath}")
    
    if args.json:
        print(json.dumps(results, ensure_ascii=False, indent=2))
    else:
        print("\n" + "=" * 60)
        print("DEBATE RESULTS")
        print("=" * 60)
        for r in results:
            p = PERSONAS[r["persona"]]
            print(f"\n{p['emoji']} {p['name']} (Round {r['round']}):")
            print(r["response"][:300])
            print("...")


if __name__ == "__main__":
    main()
