#!/usr/bin/env python3
"""
AGI Glossary Bot — English Edition
Pick one AGI concept per day, generate an English explanation + image, and post to X.
Part of the AGI Knowledge Hub 多言語化 initiative.
"""

import argparse
import json
import os
import sys
import subprocess
from pathlib import Path
from datetime import datetime, timezone, timedelta

WORKSPACE = Path(__file__).parent.parent.parent.parent
DATA_DIR = WORKSPACE / "data"
STATE_FILE = DATA_DIR / "agi-glossary-en-state.json"
FAL_KEY_FILE = WORKSPACE / "fal-key.txt"

JST = timezone(timedelta(hours=9))

AGI_TERMS = [
    {"term": "Reward Hacking", "desc": "AI finds unexpected shortcuts to maximize rewards, exploiting gaps between the specified objective and the true intent."},
    {"term": "Emergent Abilities", "desc": "Large language models suddenly exhibit capabilities not present in smaller models, arising from scale alone."},
    {"term": "Scaling Laws", "desc": "Predictable relationships between model performance and factors like parameter count, dataset size, and compute."},
    {"term": "Chain-of-Thought", "desc": "Prompting models to reason step-by-step, dramatically improving performance on complex problems."},
    {"term": "Constitutional AI", "desc": "An alignment technique where AI systems follow a set of principles to self-correct and refine their outputs."},
    {"term": "RLHF", "desc": "Reinforcement Learning from Human Feedback — training AI to align with human preferences through reward signals."},
    {"term": "Mixture of Experts", "desc": "Routing inputs to specialized sub-models, activating only relevant experts for efficiency and performance."},
    {"term": "In-Context Learning", "desc": "Learning new tasks from examples provided in the prompt, without any parameter updates."},
    {"term": "Instruction Tuning", "desc": "Fine-tuning models on instruction-following data to better understand and execute user intent."},
    {"term": "Alignment", "desc": "The challenge of ensuring AI systems pursue goals that match human values and intentions."},
    {"term": "Frontier Models", "desc": "The most advanced AI models at the cutting edge, posing novel risks and capabilities."},
    {"term": "Agentic AI", "desc": "AI systems that autonomously plan, execute, and iterate — moving from passive responders to active agents."},
    {"term": "Tool Use", "desc": "LLMs calling external tools (search, calculators, APIs) to extend their capabilities beyond text generation."},
    {"term": "Retrieval-Augmented Generation", "desc": "RAG — grounding AI outputs by retrieving relevant documents from external knowledge bases at inference time."},
    {"term": "World Model", "desc": "An AI's internal representation of how environments evolve, enabling prediction and planning."},
    {"term": "Test-Time Compute", "desc": "Allocating additional computation during inference for deeper reasoning and higher accuracy."},
    {"term": "Sparse Attention", "desc": "Efficiently processing long contexts by computing attention only over relevant token subsets."},
    {"term": "Process Reward Model", "desc": "Evaluating each step of reasoning rather than just the final answer, rewarding correct thinking processes."},
    {"term": "Synthetic Data", "desc": "Training AI models on data generated by other AI systems, amplifying available training resources."},
    {"term": "Grokking", "desc": "Delayed generalization — models suddenly improve after extended overtraining, long past traditional stopping points."},
    {"term": "Model Distillation", "desc": "Compressing knowledge from large models into smaller, faster ones while preserving performance."},
    {"term": "Multimodal", "desc": "Unified processing of text, images, audio, and other modalities within a single model architecture."},
    {"term": "Self-Play", "desc": "AI improving through competition against itself, discovering novel strategies without human data."},
    {"term": "Tree of Thoughts", "desc": "Exploring multiple reasoning paths as a branching tree to find optimal solutions through deliberate search."},
    {"term": "Mechanistic Interpretability", "desc": "Reverse-engineering neural networks to understand how internal circuits produce specific behaviors."},
    {"term": "Representation Engineering", "desc": "Manipulating model internals to control outputs — reading and writing representations for alignment."},
    {"term": "Catastrophic Forgetting", "desc": "Learning new tasks causes dramatic performance loss on previously mastered ones."},
    {"term": "Zero-Shot Learning", "desc": "Performing tasks without any examples or demonstrations, relying purely on pre-trained knowledge."},
    {"term": "Gradient Accumulation", "desc": "Simulating large batch training by accumulating gradients across multiple forward passes."},
    {"term": "Softmax Temperature", "desc": "A parameter controlling output diversity — low temperature for deterministic, high for creative generation."},
]


def load_state():
    if STATE_FILE.exists():
        return json.loads(STATE_FILE.read_text())
    return {"posted_terms": [], "last_post_date": None}


def save_state(state):
    STATE_FILE.parent.mkdir(parents=True, exist_ok=True)
    STATE_FILE.write_text(json.dumps(state, ensure_ascii=False, indent=2))


def select_term(state):
    posted = set(state.get("posted_terms", []))
    available = [t for t in AGI_TERMS if t["term"] not in posted]
    if not available:
        available = AGI_TERMS
        state["posted_terms"] = []
    today = datetime.now(JST).strftime("%Y-%m-%d")
    seed = hash(today) % len(available)
    return available[seed]


def generate_tweet(term_info):
    term = term_info["term"]
    desc = term_info["desc"]
    return f"""🧠 AGI Glossary — "{term}"

{desc}

#AGI #AI #ONIZUKA_AGI"""


def generate_image_prompt(term_info):
    term = term_info["term"]
    return (
        f"A clean, modern infographic illustration about the AI concept '{term}'. "
        f"Abstract, minimalist style with soft gradients. "
        f"Professional, educational, tech-themed. "
        f"Dark background with glowing neural network elements. "
        f"No text or words in the image."
    )


def run_cmd(cmd, timeout=120):
    result = subprocess.run(cmd, capture_output=True, text=True, timeout=timeout,
                           env=os.environ.copy())
    return result


def main():
    parser = argparse.ArgumentParser(description="AGI Glossary Bot — English Edition")
    parser.add_argument("command", nargs="?", default="run",
                        choices=["run", "select", "preview"],
                        help="Command to execute")
    parser.add_argument("--dry-run", action="store_true", help="Don't post to X")
    parser.add_argument("--no-image", action="store_true", help="Skip image generation")
    args = parser.parse_args()

    state = load_state()
    term_info = select_term(state)

    if args.command == "select":
        print(f"Term: {term_info['term']}")
        print(f"Desc: {term_info['desc']}")
        return

    tweet_text = generate_tweet(term_info)

    if args.command == "preview":
        print("=== Tweet ===")
        print(tweet_text)
        print()
        print("=== Image Prompt ===")
        print(generate_image_prompt(term_info))
        return

    # Full pipeline
    print(f"[1/3] Selected term: {term_info['term']}")

    # Generate image
    image_url = None
    if not args.no_image:
        print("[2/3] Generating image...")
        try:
            gen_script = WORKSPACE / "skills" / "nano-banana-2" / "scripts" / "generate.py"
            if not gen_script.exists():
                print("  nano-banana-2 generate.py not found, skipping image")
            else:
                prompt = generate_image_prompt(term_info)
                fal_key = FAL_KEY_FILE.read_text().strip() if FAL_KEY_FILE.exists() else ""
                env = {**os.environ, "FAL_KEY": fal_key}
                result = subprocess.run(
                    ["uv", "run", str(gen_script),
                     "--prompt", prompt,
                     "--aspect-ratio", "1:1",
                     "--resolution", "1K",
                     "--output-format", "png",
                     "--save", "--json"],
                    capture_output=True, text=True, timeout=120, env=env
                )
                if result.returncode == 0:
                    for line in result.stdout.strip().split('\n'):
                        line = line.strip()
                        if line.startswith('{'):
                            try:
                                gen_result = json.loads(line)
                                image_url = gen_result.get("images", [{}])[0].get("url")
                                break
                            except json.JSONDecodeError:
                                continue
                    if image_url:
                        print(f"  Image: {image_url}")
                    else:
                        print("  No image URL found in output")
                else:
                    print(f"  Image generation failed: {result.stderr[:200]}")
        except Exception as e:
            print(f"  Image error: {e}")

    if args.no_image or not image_url:
        print("[2/3] Skipping image generation")

    # Post to X
    if args.dry_run:
        print("[3/3] DRY RUN — would post:")
        print(tweet_text)
        if image_url:
            print(f"  Image: {image_url}")
    else:
        print("[3/3] Posting to X...")
        try:
            x_write_script = WORKSPACE / "skills" / "x-write" / "scripts" / "x_write.py"
            cmd = ["uv", "run", str(x_write_script), "tweet", "--text", tweet_text]
            if image_url:
                cmd.extend(["--media", image_url])
            result = subprocess.run(cmd, capture_output=True, text=True, timeout=60)
            if result.returncode == 0:
                print("  Posted successfully!")
                state["posted_terms"].append(term_info["term"])
                state["last_post_date"] = datetime.now(JST).isoformat()
                save_state(state)
            else:
                print(f"  Post failed: {result.stderr[:200]}")
        except Exception as e:
            print(f"  Post error: {e}")

    print(f"\nDone! Term: {term_info['term']}")


if __name__ == "__main__":
    main()
